<?php
    return[
        'pagination' => 20,
        'api_pagination' => 20,
        'common' => [
            'messages' => [
                'success_add' => 'Record added successfully.',
                'success_update' => 'Record updated successfully.',
                'success_fetch' => 'Record fetched successfully.',
                'success_delete' => 'Record deleted successfully.',
                'error' => 'Error while processing operation',
                'credential_not_found' =>'Credential not found',
                'invalid_email_password' =>'Invalid email and password',
                'you_have_successfully_logged_in' => 'You have successfully logged in',
                'your_account_has_been_suspended' => 'Your account has been suspended',
            ]
        ],
        'voice_accent' => ['ar','bn-BD','bn-IN','bs','ca','cs-CZ','cy','da-DK','de-DE','el-GR','en-AU','en-GB','en-IN','en-NG','en-US','es-ES','es-US','et-EE','fil-PH','fi-FI','fr-CA','fr-FR','gu-IN','hi-IN','hu-HU','id-ID','it-IT','ja-JP','jv-ID','km-KH','kn-IN','ko-KR','ku','la','ml-IN','mr-IN','nb-NO','ne-NP','nl-NL','pl-PL','pt-BR','pt-PT','ro-RO','ru-RU','si-LK','sk-SK','sq','sr','su-ID','sv-SE','sw','ta-IN','te-IN','th-TH','tr-TR','uk-UA','ur-PK','vi-VN','yue-HK','zh-CN','zh-TW'],
        'font_family' => [ 
            'Times New Roman',
            'serif',
            'Times',
            'Arial',
            'Helvetica',
            'sans-serif',
            'Lucida Console',
            'Courier New',
            'monospace',
            'cursive',
            'Brush Script MT',
        ],
        'speech_voice' =>[
            "en-GB-Neural2-A" => "English (UK) Neural Voice A (FEMALE)",
            "en-GB-Neural2-B" => "English (UK) Neural Voice B (MALE)",
            "en-GB-Neural2-C" => "English (UK) Neural Voice C (FEMALE)",
            "en-GB-Neural2-D" => "English (UK) Neural Voice D (MALE)",
            "en-GB-Neural2-F" => "English (UK) Neural Voice F (FEMALE)",
            "en-GB-News-G" => "English (UK) News Voice G (FEMALE)",
            "en-GB-News-H" => "English (UK) News Voice H (FEMALE)",
            "en-GB-News-I" => "English (UK) News Voice I (FEMALE)",
            "en-GB-News-J" => "English (UK) News Voice J (MALE)",
            "en-GB-News-K" => "English (UK) News Voice K (MALE)",
            "en-GB-News-L" => "English (UK) News Voice L (MALE)",
            "en-GB-News-M" => "English (UK) News Voice M (MALE)",
            "en-GB-Standard-A" => "English (UK) Standard Voice A (FEMALE)",
            "en-GB-Standard-B" => "English (UK) Standard Voice B (MALE)",
            "en-GB-Standard-C" => "English (UK) Standard Voice C (FEMALE)",
            "en-GB-Standard-D" => "English (UK) Standard Voice D (MALE)",
            "en-GB-Standard-F" => "English (UK) Standard Voice F (FEMALE)",
            "en-GB-Studio-B" => "English (UK) Studio Voice B (MALE)",
            "en-GB-Studio-C" => "English (UK) Studio Voice C (FEMALE)",
            "en-GB-Wavenet-A" => "English (UK) Wavenet Voice A (FEMALE)",
            "en-GB-Wavenet-B" => "English (UK) Wavenet Voice B (MALE)",
            "en-GB-Wavenet-C" => "English (UK) Wavenet Voice C (FEMALE)",
            "en-GB-Wavenet-D" => "English (UK) Wavenet Voice D (MALE)",
            "en-GB-Wavenet-F" => "English (UK) Wavenet Voice F (FEMALE)"
        ],
        'news_api_language' => [ 
            'en'=>'English',
            'ar'=>'Arabic',
            'de'=>'German',
            'es'=>'Spanish',
            'fr'=>'French',
            'he'=>'Hebrew',
            'it'=>'Italian',
            'nl'=>'Dutch',
            'no'=>'Norwegian',
            'pt'=>'Portuguese',
            'ru'=>'Russian',
            'se'=>'Northern Sami',
            'ud'=>'ud',
            'zh'=>'Chinese'
        ],
    ]
?>